### ISSUE TITLE
pull access denied for dila2sql-api

### ISSUE THREAD

**Issue by ArmandGiraud** [SocialGouv/legi.py#27]
Hello,
quand j'essaie de compose-up j'ai une erreur docker.
J'ai loupé quelquechose?

- logs:

```docker-compose up -d```
Pulling api (dila2sql-api:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling api (dila2sql-api:)...
ERROR: pull access denied for dila2sql-api, repository does not exist or may require 'docker login'

merci pour ton aide

**Comment by adipasquale** [comment]
woups je vais regarder @ArmandGiraud

**Comment by adipasquale** [comment]
should be fixed @ArmandGiraud 
J'ai aussi mis à disposition un dump PostgreSQL https://api.dila2sql.num.social.gouv.fr/dila2sql_dump_KALI.sql que tu peux remonter sur une base locale avec psql si tu veux éviter d'avoir à lancer tout le bazar. 

Le dump n'est pas super frais malheureusment il doit avoir un petit mois. L'idée c'est d'automatiser ça et de fournir des dumps mis à jour quotidiennement pour toutes les DBs

**Comment by ArmandGiraud** [comment]
Merci beaucoup !
ça marche chez moi!
tu peux fermer :)
